databases:
  - name: fanart-expo
    databaseName: fanart-expo-db
    user: ajs.amandasmith@gmail.com

services:
  - type: web
    name: fanart-expo
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false